import argparse
import os
from rich.console import Console
from rich.panel import Panel
from rich.syntax import Syntax
from rich.markdown import Markdown

from modules.log_parser import parse_logs
from modules.code_extractor import extract_location, get_code_context
from modules.engine import analyze_with_ai

console = Console()

def main():
    parser = argparse.ArgumentParser(description="AI Root Cause Analysis CLI")
    parser.add_argument("logfile", help="Path to the log file you want to analyze")
    args = parser.parse_args()
    
    if not os.path.exists(args.logfile):
        print(f"Error: The file '{args.logfile}' does not exist.")
        return

    print(f"Scanning {args.logfile} for errors...\n")
    
    errors = parse_logs(args.logfile)
    
    if not errors:
        print("No errors found! You are good to go.")
        return

    for i, error_text in enumerate(errors):
        print(f"--- Processing Error {i + 1} ---")
        
        filename, line_number = extract_location(error_text)
        
        if filename and line_number:
            print(f"📍 Detected crash in: {filename} at line {line_number}")
            
            code_context, start_line = get_code_context(filename, line_number)

            syntax = Syntax(code_context, "python", theme="monokai", line_numbers=True, start_line=start_line)
            console.print(Panel(syntax, title="🔍 Code Context", border_style="blue"))

            print("\n🧠 AI Engine Analyzing...")
            from_memory, analysis = analyze_with_ai(error_text, code_context)
            
            if from_memory:
                print("⚡ (Result loaded instantly from local memory)")
            else:
                print("🤖 (Result generated by Gemini)")
                
            md = Markdown(analysis)
            console.print(Panel(md, title="🛠️ Root Cause & Fix", border_style="magenta"))
            console.rule()
            
        else:
            print("⚠️ Could not pinpoint file/line number in this traceback.")
            
        print("="*40 + "\n")

if __name__ == "__main__":
    main()