import argparse
import os
from rich.console import Console
from rich.panel import Panel
from rich.syntax import Syntax
from rich.markdown import Markdown

from modules.log_parser import get_log_tail
from modules.code_extractor import get_full_file_code
from modules.engine import extract_error_location_with_ai, analyze_with_groq

console = Console()

def main():
    parser = argparse.ArgumentParser(description="Infer AI Agent CLI")
    parser.add_argument("logfile", help="Path to the log file you want to analyze")
    args = parser.parse_args()
    
    if not os.path.exists(args.logfile):
        console.print(f"[bold red]Error:[/bold red] The file '{args.logfile}' does not exist.")
        return

    console.rule(f"[bold cyan]Agent 1: Scanning {args.logfile} (Last 200 lines)[/bold cyan]")
    
    log_tail = get_log_tail(args.logfile)
    
    with console.status("[bold yellow]Routing Agent analyzing logs...", spinner="dots"):
        location = extract_error_location_with_ai(log_tail)
        
    if not location or "file" not in location:
        console.print("[bold red]⚠️ No clear error found in the recent logs.[/bold red]")
        return
        
    filename = location["file"]
    line_number = location.get("line", "Unknown")
    
    log_directory = os.path.dirname(os.path.abspath(args.logfile))
    
    actual_file_path = os.path.join(log_directory, filename)

    console.print(f"📍 [bold]Crash isolated to:[/bold] [cyan]{actual_file_path}[/cyan] at line [cyan]{line_number}[/cyan]")
    
    full_code = get_full_file_code(actual_file_path)
    if not full_code:
        console.print(f"[bold red]⚠️ Could not open {actual_file_path} to read code.[/bold red]")
        return

    snippet = "\n".join(full_code.split("\n")[:10]) + "\n... (File truncated for UI display)"
    syntax = Syntax(snippet, "python", theme="monokai", line_numbers=True)
    console.print(Panel(syntax, title=f"🔍 Full Code Sent to Agent ({filename})", border_style="blue"))
    
    with console.status("[bold magenta]🧠 Debugger Agent Analyzing Full File...", spinner="dots"):
        from_memory, analysis = analyze_with_groq(log_tail, full_code)
        
    if from_memory:
        subtitle = "⚡ Loaded instantly from local ChromaDB Memory"
        color = "green"
    else:
        subtitle = "🤖 Generated by Groq (Llama-3-70B)"
        color = "magenta"
        
    md = Markdown(analysis)
    console.print(Panel(md, title="🛠️ Root Cause & Fix", subtitle=subtitle, border_style=color))

if __name__ == "__main__":
    main()